import type { OrderItem, OrderStat } from "./types";

export const ORDER_STATS: OrderStat[] = [
  {
    id: "demand",
    label: "예측 수요 품목",
    value: "14",
    unit: "종",
    tag: "이번 주",
    tone: "neutral",
    icon: "package",
  },
  {
    id: "recommended",
    label: "추천 구매 품목",
    value: "3",
    unit: "종",
    tag: "조치 필요",
    tone: "warning",
    icon: "cart",
  },
  {
    id: "budget",
    label: "예상 발주 금액",
    value: "124",
    unit: "만원",
    tag: "주간",
    tone: "neutral",
    icon: "wallet",
  },
  {
    id: "saving",
    label: "AI 절감 효과",
    value: "31",
    unit: "만원",
    tag: "선구매",
    tone: "success",
    icon: "sparkles",
  },
];

export const ORDER_ITEMS: OrderItem[] = [
  {
    id: 1,
    name: "양파",
    supplier: "푸른들 농산",
    price: 186000,
    weeklyDemand: 142,
    stock: 38,
    recommended: 120,
    fit: 96,
    note: "이번 주 양파 120kg 구매를 권장해요.",
  },
  {
    id: 2,
    name: "돼지고기 앞다리",
    supplier: "한울 축산",
    price: 742000,
    weeklyDemand: 96,
    stock: 64,
    recommended: 80,
    fit: 92,
    note: "제육·돈까스 메뉴로 수요 증가, 80kg 추가 필요.",
  },
  {
    id: 3,
    name: "고등어",
    supplier: "동해 수산",
    price: 312000,
    weeklyDemand: 30,
    stock: 22,
    recommended: 24,
    fit: 88,
    note: "목요일 생선구이 대비 24kg 보충 권장.",
  },
  {
    id: 4,
    name: "친환경 쌀",
    supplier: "신선마루",
    price: 0,
    weeklyDemand: 240,
    stock: 480,
    recommended: 0,
    fit: 71,
    note: "재고 충분, 이번 주 구매 불필요.",
  },
];
