import { AppShell } from "@/widgets/app-shell";

const stats = [
  { label: "Active projects", value: "24", detail: "+4 this week" },
  { label: "Pending reviews", value: "12", detail: "3 due today" },
  { label: "Automation health", value: "98%", detail: "All systems steady" },
];

const activity = [
  "Design handoff imported for review",
  "Weekly report generated by AI",
  "Project timeline updated",
];

export default function DashboardView() {
  return (
    <AppShell>
      <section className="grid gap-4 md:grid-cols-3">
        {stats.map((stat) => (
          <article key={stat.label} className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm">
            <p className="text-sm font-medium text-slate-500">{stat.label}</p>
            <p className="mt-3 text-3xl font-semibold tracking-tight text-slate-950">{stat.value}</p>
            <p className="mt-2 text-sm text-slate-500">{stat.detail}</p>
          </article>
        ))}
      </section>

      <section className="mt-6 grid gap-6 lg:grid-cols-[1fr_22rem]">
        <div className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm">
          <div className="flex items-center justify-between gap-4">
            <div>
              <h2 className="text-lg font-semibold text-slate-950">Workspace pulse</h2>
              <p className="mt-1 text-sm text-slate-500">Shared layout shell preview area</p>
            </div>
            <span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-700">
              LIVE
            </span>
          </div>
          <div className="mt-8 grid h-64 place-items-center rounded-lg border border-dashed border-slate-300 bg-slate-50">
            <div className="text-center">
              <p className="text-sm font-semibold uppercase tracking-wider text-slate-400">Dashboard canvas</p>
              <p className="mt-2 text-2xl font-semibold text-slate-950">Common shell ready</p>
            </div>
          </div>
        </div>

        <aside className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="text-lg font-semibold text-slate-950">Recent activity</h2>
          <div className="mt-5 space-y-4">
            {activity.map((item) => (
              <div key={item} className="flex gap-3">
                <span className="mt-1 size-2 rounded-full bg-cyan-600" aria-hidden="true" />
                <p className="text-sm leading-6 text-slate-600">{item}</p>
              </div>
            ))}
          </div>
        </aside>
      </section>
    </AppShell>
  );
}
