import type { Ingredient } from "./types";

export const MOCK_INGREDIENTS: Ingredient[] = [
  {
    id: "1",
    name: "친환경 백미",
    category: "곡물",
    quantity: 480,
    unit: "kg",
    expiryDate: "2026-09-30",
    safetyStock: 200,
    status: "정상",
  },
  {
    id: "2",
    name: "양파",
    category: "농산물",
    quantity: 38,
    unit: "kg",
    expiryDate: "2026-06-20",
    safetyStock: 60,
    status: "부족",
  },
  {
    id: "3",
    name: "대파",
    category: "농산물",
    quantity: 12,
    unit: "kg",
    expiryDate: "2026-06-15",
    safetyStock: 25,
    status: "긴급",
  },
  {
    id: "4",
    name: "돼지고기 앞다리",
    category: "축산",
    quantity: 64,
    unit: "kg",
    expiryDate: "2026-06-14",
    safetyStock: 40,
    status: "임박",
  },
  {
    id: "5",
    name: "닭다리살",
    category: "축산",
    quantity: 88,
    unit: "kg",
    expiryDate: "2026-06-18",
    safetyStock: 50,
    status: "정상",
  },
  {
    id: "6",
    name: "고등어",
    category: "수산",
    quantity: 22,
    unit: "kg",
    expiryDate: "2026-06-13",
    safetyStock: 20,
    status: "임박",
  },
  {
    id: "7",
    name: "배추김치",
    category: "가공",
    quantity: 140,
    unit: "kg",
    expiryDate: "2026-07-10",
    safetyStock: 80,
    status: "정상",
  },
  {
    id: "8",
    name: "시금치",
    category: "농산물",
    quantity: 9,
    unit: "kg",
    expiryDate: "2026-06-14",
    safetyStock: 15,
    status: "긴급",
  },
  {
    id: "9",
    name: "롱나물",
    category: "농산물",
    quantity: 31,
    unit: "kg",
    expiryDate: "2026-06-16",
    safetyStock: 20,
    status: "정상",
  },
  {
    id: "10",
    name: "두부",
    category: "가공",
    quantity: 54,
    unit: "모",
    expiryDate: "2026-06-15",
    safetyStock: 40,
    status: "정상",
  },
  {
    id: "11",
    name: "계란",
    category: "축산",
    quantity: 36,
    unit: "판",
    expiryDate: "2026-06-22",
    safetyStock: 30,
    status: "정상",
  },
  {
    id: "12",
    name: "식용유",
    category: "가공",
    quantity: 18,
    unit: "L",
    expiryDate: "2027-01-31",
    safetyStock: 40,
    status: "부족",
  },
  {
    id: "13",
    name: "현미",
    category: "곡물",
    quantity: 32,
    unit: "kg",
    expiryDate: "2026-10-15",
    safetyStock: 120,
    status: "긴급",
  },
];
