import type { Supplier } from "./types";

export const SUPPLIERS: Supplier[] = [
  {
    id: 1,
    name: "푸르름 농산",
    category: "채소·과일",
    distance: "4.2 km",
    rating: 4.8,
    reviews: 214,
    price: "보통",
    delivery: "당일",
    recommended: true,
    accent: "bg-emerald-500",
    initial: "푸",
  },
  {
    id: 2,
    name: "한울 축산",
    category: "육류",
    distance: "7.8 km",
    rating: 4.7,
    reviews: 168,
    price: "약간 높음",
    delivery: "익일",
    recommended: true,
    accent: "bg-red-500",
    initial: "한",
  },
  {
    id: 3,
    name: "동해 수산",
    category: "수산물",
    distance: "12.4 km",
    rating: 4.5,
    reviews: 96,
    price: "보통",
    delivery: "익일",
    recommended: false,
    accent: "bg-blue-600",
    initial: "동",
  },
  {
    id: 4,
    name: "행복드림 베이커리",
    category: "제과·제빵",
    distance: "3.1 km",
    rating: 4.6,
    reviews: 142,
    price: "낮음",
    delivery: "당일",
    recommended: false,
    accent: "bg-amber-500",
    initial: "행",
  },
  {
    id: 5,
    name: "신선마루 종합식자재",
    category: "종합",
    distance: "9.5 km",
    rating: 4.4,
    reviews: 320,
    price: "낮음",
    delivery: "익일",
    recommended: false,
    accent: "bg-violet-500",
    initial: "신",
  },
];
